/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_stayclassy_sc_recurring_profileTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_stayclassy_sc_recurring_pa1vTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new stayclassy__sc_recurring_profile__c());
    }
}